### ISSUE TITLE
litedoged-ARM-RasberryPI.zip

### ISSUE THREAD

**Issue by pny1312** [ldoge/LDOGE#32]
litedoged-ARM-RasberryPI.zip extract to "litedoged", how to run the wallet?
./litedoged: command not found

**Comment by DedaDev** [comment]
`chmod +x litedoged`

**Comment by skyrawrcode** [comment]
I also have this issue it’s being investigated but the developers machine got angry and so there is some delay. Thank you for your patience.

**Comment by vashshawn** [comment]
> litedoged-ARM-RasberryPI.zip extract to "litedoged", how to run the wallet?
> ./litedoged: command not found

it wont run on a rPI if it is under 2gb and the blockchain is over 2 gb space used up too. Confirmed to run on a rPi 4
