### ISSUE TITLE
can also not run with history at all

### ISSUE THREAD

**Issue by katesalazar** [ldoge/LDOGE#35]
https://github.com/ldoge/LDOGE/wiki/LiteDoge-full-node-copy-paste-installation-guide#clear-history

for bash in particular, this can be achieved at the beginning, not only at the end

https://www.gnu.org/software/bash/manual/bash.html#index-HISTFILE

used like:

    $ HISTFILE=/dev/null bash
    $ _

**Comment by vashshawn** [comment]
added the command thank you i checked out the website

**Comment by katesalazar** [comment]
you killed the format dude

**Comment by vashshawn** [comment]
how DId I kill the format?

**Comment by katesalazar** [comment]
you copy pasted the lines before your
`cat /dev/null > ~/.bash_history ...`
instead of after it,
and the preformatted block turned normal text
killing the line break between "$ HISTFILE=/dev/null bash" and "$ _"

**Comment by vashshawn** [comment]
used like $ HISTFILE=/dev/null

that makes bash stop recording new history

history -c

that erases any previous history
