### ISSUE TITLE
use ccache

### ISSUE THREAD

**Issue by katesalazar** [ldoge/LDOGE#51]
LDOGE lists ccache here:
https://github.com/ldoge/LDOGE/blob/3232f3ec16daa19fc4b071c0e01bf742757591a6/.github/workflows/build.yml#L79

however, it won't use it locally

**Comment by vashshawn** [comment]
would it be best to leave it out when suggesting to build in build instructions then?

**Comment by katesalazar** [comment]
meh, maybe

probably devs are the most affected by this, so do as you better please
maybe
even close as-is

sadly I'm a bit swamped these days and can't assess this any better

**Comment by vashshawn** [comment]
this is apart of having to do with windows, has nothing to with building with linux. Its not a issue.
static builds vs non static builds
CCACHE_SIZE: 100M
    CCACHE_TEMPDIR: /tmp/.ccache-temp
    CCACHE_COMPRESS: 1
