### ISSUE TITLE
make headless tries to do stuff, however qmake headless does not

### ISSUE THREAD

**Issue by katesalazar** [ldoge/LDOGE#52]
https://github.com/ldoge/LDOGE/blob/3232f3ec16daa19fc4b071c0e01bf742757591a6/doc/build-unix.txt#L18

Did you mean "make -f makefile.unix" here?

**Comment by vashshawn** [comment]
yes I did mean to put make not qmake, thank you for pointing that out, I corrected it and updated the qt instructions also.
