### ISSUE TITLE
allow boost 1.67.0

### ISSUE THREAD

**Issue by katesalazar** [ldoge/LDOGE#53]
something similar to 
https://github.com/zetacoin/zetacoin/issues/12
happens when trying to build litedoged
mostly "no matching function for call to rpclisten"

**Comment by vashshawn** [comment]
Added the changes let me know if it works when making a debain build

**Comment by katesalazar** [comment]
I was able to build the Qt and Qt-less binaries at the new tag at 9c0f9fd3b5 without trouble, however debian 10 reaches security EOL very soon so I should migrate to a yet a newer linux soon.
