### ISSUE TITLE
addnode should default to nDefaultPort

### ISSUE THREAD

**Issue by katesalazar** [ldoge/LDOGE#61]
addnode WAHTERVER add

should default to:
https://github.com/ldoge/LDOGE/blob/6aa4f09d7b7109688f70a5809ca31e87e62337f1/src/chainparams.cpp#L56

I THINK THIS IS DONE IN src/net.cpp:CNode * ConnectNode(2):
https://github.com/ldoge/LDOGE/blob/6aa4f09d7b7109688f70a5809ca31e87e62337f1/src/net.cpp#L347-L402

**Comment by vashshawn** [comment]
> ```
> addnode WAHTERVER add
> ```
> 
> should default to:
> 
> https://github.com/ldoge/LDOGE/blob/6aa4f09d7b7109688f70a5809ca31e87e62337f1/src/chainparams.cpp#L56
> 
> I THINK THIS IS DONE IN src/net.cpp:CNode * ConnectNode(2):
> 
> https://github.com/ldoge/LDOGE/blob/6aa4f09d7b7109688f70a5809ca31e87e62337f1/src/net.cpp#L347-L402

that command is already available on ldoge

**Comment by katesalazar** [comment]
> that command is already available on ldoge

corect
