### ISSUE TITLE
Build not working for Ubuntu

### ISSUE THREAD

**Issue by gangesh** [ldoge/LDOGE#66]
Error:

Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qt5-default' has no installation candidate

**Comment by katesalazar** [comment]
https://askubuntu.com/a/1335187

**Comment by vashshawn** [comment]
https://github.com/ldoge/LDOGE/blob/master/doc/readme-qt.rst please read this to refer how to build with debain/unix, it goes over each part, step by step and how to turn features on or off before making the build. If you have issues still please contact the dev team on discord at https://discord.gg/dVWy7MqE2J
